### ISSUE TITLE
Update categories under MRI

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/cneuromod_docs#13]
I find it strange to have acquisition parameters listed under the parent category "BIDS formatting". I suggest instead:
- MRI
  - Image acquisition
    - MR scanner
    - Personalized head cases
    - Sequence parameters
    - BIDS formatting
etc.

**Comment by pbellec** [comment]
This has been fixed.

It now goes:
 * MRI 
   * Image acquisition
     * Scanner 
     * Personal headcases 
     * (soon to be added) Video game controller 
   * Sequences 
     * Functional sequences
     * Brain anatomical sequences 
     * Spinal cord anatomical sequences
(...) 

The reference to BIDS formatting is now a part of DATASETS

**Comment by jcohenadad** [comment]
i find it confusing to move sequences out of image acquisition (sequences are part of the acquisition)-- how about:

- MRI acquisition
  - System
  - Personal headcases
  - (soon to be added) Video game controller
  - Sequences
    - Functional sequences
    - Brain anatomical sequences
    - Spinal cord anatomical sequences
    - (...)
