### ISSUE TITLE
B1 map does not exist

### ISSUE THREAD

**Issue by evaalonsoortiz** [courtois-neuromod/cneuromod_docs#16]
The documentation for the Brain Anatomical Sequences has:
B1+ field map (duration 0:21 min, voxel size = 6 mm isotropic)

This image does not appear to exist for any of the subjects and could be removed from the documentation.

**Comment by julieaboyle1** [comment]
thanks Eva! We will remove it.

**Comment by evaalonsoortiz** [comment]
I was premature in opening this issue, the dicoms do exist, they just weren't converted during the dcm2bids conversion.

**Comment by jcohenadad** [comment]
@evaalonsoortiz can you open an issue to (i) re-add the b1 map in the doc and (ii) fix the dcm2bids conversion. thanks!
