### ISSUE TITLE
Add reference to RTD site

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod_docs#2]
It would be great to (create ? and) add a link to the RTD site in the repo description on GitHub, as well as in the README.

One fun suggestion in this vein: [ReadTheDocs recently released a beta workflow that can run on every PR](https://blog.readthedocs.com/building-docs-for-pull-requests/) so you see an updated version of the documentation with your proposed changes. You can see it in action on tedana, [for example here](https://external-builds.readthedocs.io/html/tedana/465/index.html).

**Comment by bpinsard** [comment]
added the link.
Will have a look at the option you are describing.

**Comment by emdupre** [comment]
Sounds good ! If you decide to move forward with it, all you should need to do is email them directly at support@readthedocs.org and ask for it to be enabled.

**Comment by pbellec** [comment]
the links have been added.

I love the feature integrating updated docs with PR.
I have contacted RTD team to request adding the integration to this repo.

Thanks for the tip @emdupre

**Comment by pbellec** [comment]
btw @emdupre the RTD feature is now activated, and should appear in new pull requests.

Thanks a lot for pointing it out!
