### ISSUE TITLE
specify anatomical location for spinal cord imaging

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/cneuromod_docs#20]
I think it would be valuable to specify the spinal level covered for each acquisition of the spinal cord protocol.

**Comment by jcohenadad** [comment]
not a big fan:
- spinal level is difficult to find (or maybe you meant "vertebral" level?)
- prone to error from MR tech
- [automated tools](https://github.com/neuropoly/spinalcordtoolbox) can find the level

i would just indicate that the acquisition is spinal, in case of dual brain-spine session

**Comment by pbellec** [comment]
Sounds good @jcohenadad 

@bpinsard can you confirm that spinal cord images include a `cspine` tag in the datalad? 
It seems to be the case https://github.com/courtois-neuromod/anat/tree/0e06985d48eebfd62b231c5fee4640143e92d29b/sub-01/ses-001/anat

**Comment by bpinsard** [comment]
Yes, I have to add a `bp-cspine` tag to differentiate from the brain images with the same contrast. 
This tag is not yet BIDS-valid, it is in a BIDS extension (MIDS).
