### ISSUE TITLE
Update dataset access information with need for GitHub SSH key

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod_docs#22]
In the [Downloading the dataset](http://docs.cneuromod.ca/en/latest/ACCESS.html#downloading-the-dataset) section, the description currently only references the need for a SSH key on the UNF git (hosted with gitea). However, since the documentation itself is separately hosted on GitHub, users need to have their public SSH keys on _both_ the UNF git and GitHub. Trying to access the dataset with only the an SSH key for the UNF git results in the following error:

```bash
git@github.com: Permission denied (publickey).
ConnectionOpenFailedError: command '['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/emdupre/.cache/datalad/sockets/be7bf7bb', 'git@github.com']' failed with exitcode 255
Failed to open SSH connection (could not start ControlMaster process)
```

Adding information on both SSH keys could help avoid this error for some users !

**Comment by pbellec** [comment]
This is going to be simpler now that all the data is on github. But we still need to edit the docs to remove references to UNF git, and replace it by github.

**Comment by pbellec** [comment]
I actually did this update in PR https://github.com/courtois-neuromod/cneuromod_docs/pull/30 recently. So it should be all good now.
