### ISSUE TITLE
add a section on subjects demographics

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#26]

**Comment by julieaboyle1** [comment]
- [ ] Add to section where we  describe participants

**Comment by pbellec** [comment]
ping @julieaboyle1

**Comment by julieaboyle1** [comment]
JAB add: "Six healthy participants (aged 31 and 47 at the time of recruitment), 3 men (sub-01, 02 & 05) and 3 women (sub-03, 04 & 06) agreed to and consented to participate in the Courtois Neuromod Project for at least 5 years. Three of the participants reported being native francophone speakers (sub-01, 02 & 04), one as being a native anglophone (sub-06) and two as bilingual native speakers (sub-03 & 05).
All participants reported being in good general health, all had normal hearing and vision for their age, and all were MRI and MEG compatible. "
