### ISSUE TITLE
Link to DataLad Handbook

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod_docs#3]
In the section on [Downloading the dataset](http://docs.cneuromod.ca/en/latest/ACCESS.html#downloading-the-dataset) it might be helpful to link to [the DataLad Handbook](http://handbook.datalad.org/en/latest/). 

Since DataLad can be quite confusing to first-time users, I think it'd be a valuable resource to link out -- and we could link in specific sections on e.g. updating datasets so you don't need to explain them in text !

**Comment by julieaboyle1** [comment]
thanks Elizabeth - makes sense

**Comment by bpinsard** [comment]
solved.
