### ISSUE TITLE
add acknowledgment paragraph

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#37]
with a reference to the OHBM poster.

**Comment by emdupre** [comment]
In case it's useful to see how a few other projects have approached this:

Now that fMRIPrep has grown substantially, they've moved their posters to [a dedicated section](https://fmriprep.org/en/stable/citing.html#posters). They used to be on the main page -- a structure we still have in [tedana](https://tedana.readthedocs.io/en/latest/#posters).

**Comment by pbellec** [comment]
I have added a very short paragraph. When there is a proper data paper I'll add the reference in this section https://github.com/courtois-neuromod/cneuromod_docs/blob/master/source/ACCESS.md#how-to-acknowledge
