### ISSUE TITLE
Link to BIDS

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod_docs#4]
In the [Functional sequences](http://docs.cneuromod.ca/en/latest/MRI.html#functional-sequences) section, the link to ["BIDS dataset"](https://git.unf-montreal.ca/neuromod/) goes to the dataset directly. 

This fails for users without access (or who are not logged in), so I'm not sure linking it out makes sense. Additionally, I was actually expecting that it would link to the [BIDS website](bids.neuroimaging.io). 

So, I'm wondering -- would it be worth explaining that the data are formatted in BIDS and linking to this resource at the top of the MRI section ? I might suggest that the link to the dataset goes towards the [Access](section), so it won't return a 404 for some (significant?) subset of users.

**Comment by julieaboyle1** [comment]
point noted, and I agree.  Will section on data being formatted in BIDS... @bpinsard what do you think of putting a link to the dataset in Access instead?

**Comment by julieaboyle1** [comment]
added section and removed links i the functional sequences and spinal section
