### ISSUE TITLE
add HBM poster on the 2020 release

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#44]
there should both be the text of the reference, to be cited in the suggested acknowledgment paragraph, and a pdf of the poster itself.

**Comment by julieaboyle1** [comment]
Arnaud, this goes with the reference section addition that Pierre posted above: :-)  Here is the pdf of that poster: 
[#1939_BoylePinsard_OHBM2020.pdf](https://github.com/courtois-neuromod/cneuromod_docs/files/8910231/1939_BoylePinsard_OHBM2020.pdf)
