### ISSUE TITLE
Update fMRIPrep description, link autogenerated methods

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod_docs#5]
I know that the [fMRIPrep section](https://docs.cneuromod.ca/en/latest/DERIVATIVES.html#fmriprep) in [Derivatives](https://docs.cneuromod.ca/en/latest/DERIVATIVES.html) is still being finalized, but I'd love if the final section could include:

1. The version used (from the current docs, I assume it is this one: https://github.com/poldracklab/fmriprep/releases/tag/1.5.0)
2. The exact command line arguments used in calling (though it makes sense to scrub the paths, here !)
3. The [autogenerated methods boilerplate](https://github.com/poldracklab/fmriprep/blob/278fb84c5407520cdbcc7228c8bcbe8f82d19c6c/docs/citing.rst). If / when folks use the NeuroMod data in their publications, it would be really helpful to have this section available to copy/paste !

**Comment by bpinsard** [comment]
The boilerplate is generated in the derivatives folder, and it is quite long, maybe we can indicate here where to find it in the datalad?

**Comment by pbellec** [comment]
Re point 3
Our docs have quite long documents.
And the boilerplate is a very critical piece of information.
Although I do not like having redundant information, I would add the
boilerplate in there.

Pierre Bellec

Associate professor | Professeur agrégé
Psychology Department | Département de Psychologie
Centre de recherche de l'institut Universitaire de gériatrie de Montréal (
CRIUGM <http://www.criugm.qc.ca/>)
Université de Montréal, Montréal, Canada
Phone | Téléphone +1 514 713 5596
Brain | Cerveau, Simulation, Exploration (SIMEXP) lab
<http://simexp-lab.org>

**Comment by pbellec** [comment]
Points 1 and 2 have been addressed.

Point 3 is mostly there, with a few points that still need addressing. 
It's discussed in issue #8
