### ISSUE TITLE
add cneuromod reference in the docs

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#56]
https://ww4.aievolution.com/hbm2101/index.cfm?do=abs.viewAbs&src=ext&abs=2109

**Comment by pbellec** [comment]
Boyle, J.A., Pinsard, B., et al. (June 2021). The Courtois project on neuronal modelling - 2021 data release. Poster 2224 presented at the 2021 Annual Meeting of the Organization for Human Brain Mapping, held virtually.

**Comment by pbellec** [comment]
full author list: Julie A. Boyle*, Basile Pinsard*, Emilie Dessureault, François Lespinasse, Francois Paugam, Pravish Sainath, Valentina Borghesani, Elizabeth DuPre, Eva Alonso Ortiz, Jonathan Armoza, Francois Nadeau, Samie-Jade Allard, Amal Boukhdhir, Agah Karakuzu, Jeni Chen, Arnaud Boré, Andre Cyr, Paul-Henri Mignot, Yann Harel, Sylvie Belleville, Simona Brambati, Julien Cohen-Adad, Adrian Fuente, Martin N. Hebart, Karim Jerbi, Pierre Rainville, and Pierre Bellec

**Comment by julieaboyle1** [comment]
Arnaud, this can go after the acknowledgements

**Comment by julieaboyle1** [comment]
@pbellec , I think the proper poster for this tag is our 2020 poster which highlights hcptrt, movie10 and seasons 1 & 2 of friends.  @arnaudbore  here is the reference: 

Boyle, J.A., Pinsard, B., et al. (June 2020). The Courtois project on neuronal modelling - 2020 data release. Poster 1939 was presented at the 2020 Annual Meeting of the Organization for Human Brain Mapping, held virtually.  

I cannot find a link for the abstract so here is a pdf of the abstract.
[abstract_ohbm_cneuromod_release_2020.pdf](https://github.com/courtois-neuromod/cneuromod_docs/files/8912316/abstract_ohbm_cneuromod_release_2020.pdf)
