### ISSUE TITLE
update description of the auditory stimuli presentation

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#75]
We're going to have to document our iterations, with custom earplugs, adjusted disposable ear plugs as well as the "doughnuts".

**Comment by julieaboyle1** [comment]
@pbellec  -for this release, all datasets were acquired using the old version with the cut-up yellow shells... I Have written up a blurb about the latest iteration, but thinking it might be more accurate to write up this section with the old setup... what do you think?

**Comment by pbellec** [comment]
We should mention both :/

**Comment by pbellec** [comment]
please open a PR when you can. I actually believe some of the data was collected with the final set-up of sensimetrics with the foam rings.

**Comment by julieaboyle1** [comment]
pr done... tagged you as reviewer

**Comment by pbellec** [comment]
PR merged!
