### ISSUE TITLE
participants section like inclusion/exclusion criteria

### ISSUE THREAD

**Issue by pbellec** [courtois-neuromod/cneuromod_docs#81]
Those are listed [here](Exclusion criteria include visual or
auditory problems that would prevent participants from seeing and/or hearing stimuli in the scanner,
chronic or recent (i.e. in the last two years), psychiatric or neurological problems. In addition, the
standard exclusion criteria for MRI and MEG will apply.)

**Comment by julieaboyle1** [comment]
@pbellec,  we did not explicitly screen for psychiatric or neurological issues, and I can attest that we cannot say that all participants are void of these ... we can chat about this in person - to maintain the confidentiality of the participants.  
Also, won't sure what "normal vision for their age means"... one of our subjects wears glasses, but they can put on contact lenses during the scan (additionally, unlike the hearing where we tested their hearing and thus were able to quantify that it was "normal for their age", we did not test people's vision.

**Comment by julieaboyle1** [comment]
Suggestion: visual impairments that would prevent participants from being able to see the presented stimuli in the scanner

**Comment by julieaboyle1** [comment]
done. :-)
